server:
  port: 8090
  servlet:
    context-path:  /api/
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: fea08f772bb001a15162
            client-secret: b6daab70e9336fa7d9d994ae9dd004b6a41d8c00
            redirect-uri: http://localhost:4200/login/callback/github
          google:
            client-id: 907285264927-2fuj8gmhslfphq0eems1dqib6t92j5su.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:4200/login/callback/google
            scope: openid,profile,email


  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/pay_my_buddy
    username: root
    password: admin

app:
  oauth2:
    authorizedRedirectUris: http://localhost:4200/login

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

logging:
  file:
    name: pays.logs/logfile.log
  pattern:
    file: "%d %p %c{1.} [%t] %m%n"