server:
  port: 8090
  servlet:
    context-path: /api/
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/pay_my_buddy
    username: root
    password: admin1

logging:
  file:
    name: pays.logs/logfile.log
  pattern:
    file: "%d %p %c{1.} [%t] %m%n"